### ISSUE TITLE
font-spider字体压缩

### ISSUE THREAD

**Issue by sollrei** [sollrei/mini-note#49]
```shell
npm install font-spider -g
```

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <style>
    @font-face {
      font-family: 'source';
      src:
        url('./font/SourceHanSerifCN-Heavy.ttf') format('truetype');
      font-weight: normal;
      font-style: normal;
    }
    * {
      font-family: 'source';
    }
  </style>
</head>
<body>
  这里是文字内容
</body>
</html>
```

```shell
font-spider index.html
```

**Comment by sollrei** [comment]
```css
@font-face {
  font-family: "iconfont";
  src: url('iconfont.eot'); /* IE9 */
  src: url('iconfont.eot') format('embedded-opentype'), /* IE6-IE8 */
  url('iconfont.woff') format('woff'),
  url('iconfont.ttf') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+ */
  url('iconfont.svg') format('svg'); /* iOS 4.1- */
}
```

**Comment by sollrei** [comment]
《CSS新世界》

```css
@font-face {
    font-family: Emoji;
    src: local("Apple Color Emoji"),
        local("Segoe UI Emoji"), 
        local("Segoe UI Symbol"),
        local("Noto Color Emoji");
    unicode-range: U+1F000-1F644, U+203C-3299;
}
body {
    font-family: system-ui, -apple-system, Segoe UI, Roboto, Emoji, Helvetica, Arial, sans-serif;
}
.font-serif {
    font-family: Georgia, Cambria, "Times New Roman", Times, serif;
}
.font-mono {
    font-family: Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
}
```
